{
  "uuid": "099c98d0-43b8-42bf-afc5-9a9500714fb2",
  "path": "/usr/lib/python3.12/lib2to3/fixes/fix_isinstance.py",
  "size": 1608,
  "modified": "2024-04-12T13:14:55Z",
  "created": "2025-05-28T17:29:43.455611334Z",
  "sha256_hash": "8408c92b99f50d8c4978b47a2b2155588e315f2ebbe58c160dcdcdcb89e19914",
  "file_type": "Script",
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:04.917126373Z"
}