{
  "uuid": "19923e31-c5d3-43b3-aaed-657f51ec5803",
  "path": "/lib/python3.12/lib2to3/fixes/__pycache__/fix_print.cpython-312.pyc",
  "size": 3500,
  "modified": "2025-05-28T17:29:55.212456960Z",
  "created": "2025-05-28T17:29:55.212456960Z",
  "sha256_hash": "5376521e15408c1ec4e0bb1386e881b61ff6ee6d4be48bfa81adf46433cfaa43",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:47:09.184157410Z"
}