{
  "uuid": "5ab6e42b-c9e5-4132-aa7f-91b781c1afc5",
  "path": "/lib/python3/dist-packages/launchpadlib/__pycache__/errors.cpython-312.pyc",
  "size": 276,
  "modified": "2025-02-15T08:12:22Z",
  "created": "2025-05-09T05:07:26.958789679Z",
  "sha256_hash": "cea4390acf4b7c677065828dce39c73d661f7a2c552064915df179f2751b705e",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:33.764024800Z"
}