{
  "uuid": "76503e0a-c768-4b9f-af93-481619bfe1bf",
  "path": "/lib/python3/dist-packages/uaclient/__pycache__/exceptions.cpython-312.pyc",
  "size": 33130,
  "modified": "2025-05-09T05:24:41.374146464Z",
  "created": "2025-05-09T05:24:41.374146464Z",
  "sha256_hash": "6940f21471d381e0fb20df8d929772dd6833aa0d0e30fcae8457748ccf4f81c9",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:33.857972278Z"
}