{
  "uuid": "86fa0069-1362-4878-a199-606ca7f53d76",
  "path": "/lib/python3.12/lib2to3/fixes/__pycache__/fix_basestring.cpython-312.pyc",
  "size": 770,
  "modified": "2025-05-28T17:29:55.206457038Z",
  "created": "2025-05-28T17:29:55.206457038Z",
  "sha256_hash": "c325f90dc663cf24869e9c99b17dca661c3c3cdcc1fc0676fc7d55295cbcf424",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:47:09.186254211Z"
}