{
  "uuid": "880cfa26-d6eb-4257-9938-3b488d1a73bb",
  "path": "/lib/python3/dist-packages/pip/_internal/exceptions.py",
  "size": 23634,
  "modified": "2024-10-18T17:04:47Z",
  "created": "2025-05-28T17:29:12.706015057Z",
  "sha256_hash": "4e617588d1449de49669e9b0960e9ae5ba4fbaad9c3072bb775f92be3b101dbd",
  "file_type": "Script",
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:34.356481866Z"
}