{
  "uuid": "ac2850f4-ed68-46ea-a16b-d7c3bf415beb",
  "path": "/usr/lib/python3/dist-packages/yaml/error.py",
  "size": 2533,
  "modified": "2024-03-31T17:05:25Z",
  "created": "2025-05-09T05:07:27.525781026Z",
  "sha256_hash": "021f73fada072546c4f63f8cf18a7181244ce4280b09cc15cc980b2d1176171a",
  "file_type": "Script",
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:45:26.383401380Z"
}