{
  "uuid": "dacb614e-9dcc-4eaf-b4b1-432c989d6a35",
  "path": "/usr/lib/python3.12/lib2to3/fixes/fix_throw.py",
  "size": 1582,
  "modified": "2024-04-12T13:14:55Z",
  "created": "2025-05-28T17:29:43.456611321Z",
  "sha256_hash": "fec731ed523d5cdfa21893833b52b2844eabfd1549792c1c9f8ceac2d0e8e901",
  "file_type": "Script",
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:04.921544741Z"
}